### ISSUE TITLE
Have index.ipynb instead of rst in general?

### ISSUE THREAD

**Issue by ceball** [pyviz/nbsite#23]
And maybe even no rst files at all in the template?

**Comment by jbednar** [comment]
I think index.ipynb will be more useful in most cases, because it gives a launching-off point from within Jupyter, linking to each individual notebook.  The links when it goes to the website are fine, but if those are generated using .rst then there's nothing that links the actual notebooks to a table of contents.  If we swtitch to index.ipynb, then we get rid of more .rst that we have to maintain, while providing easier usage from within Jupyter.
